# Generated by Django 5.1.4 on 2025-07-10 14:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='project',
            table='project',
        ),
        migrations.AlterModelTable(
            name='ticket',
            table='ticket',
        ),
    ]
